# Generated by Django 4.2 on 2023-09-06 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.URLField()),
                ('year_founded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('industry', models.CharField(max_length=250)),
                ('size_range', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('linkedin_url', models.URLField()),
                ('current_employee_estimate', models.PositiveIntegerField()),
                ('total_employee_estimate', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
